databases:
  - name: donationdb
    plan: free
    databaseName: donation
    user: donation

services:
  - type: web
    plan: free
    name: DonationTracker
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn DonationTracker.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: donationdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4