# Generated by Django 5.0.4 on 2024-05-05 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateApp', '0003_alter_donation_amount_alter_donation_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_donors', to='donateApp.donor'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
