# Generated by Django 5.0.4 on 2024-05-05 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateApp', '0004_alter_donation_donor_alter_event_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donateApp.donor'),
        ),
    ]
