# Generated by Django 5.0.4 on 2024-05-05 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateApp', '0005_alter_donation_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFlyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flyer', models.ImageField(blank=True, default='default.png', null=True, upload_to='events_flyers')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donateApp.event')),
            ],
            options={
                'verbose_name_plural': 'EventFlyers',
            },
        ),
    ]
