# Generated by Django 5.0.4 on 2024-05-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateApp', '0007_remove_eventflyer_flyer_eventflyer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventflyer',
            name='image',
            field=models.ImageField(default='default.png', upload_to='events_flyers'),
        ),
    ]
