# Generated by Django 5.0.4 on 2024-05-05 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateApp', '0008_alter_eventflyer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventflyer',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_flyer', to='donateApp.event'),
        ),
    ]
