# Generated by Django 5.0.4 on 2024-05-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateApp', '0009_alter_eventflyer_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default.png', upload_to='events_flyers'),
        ),
        migrations.DeleteModel(
            name='EventFlyer',
        ),
    ]
