# Generated by Django 5.0.4 on 2024-05-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donateApp', '0010_event_image_delete_eventflyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='flyer',
        ),
    ]
